version: "3.5"
services:
    bot:
        build: .
        volumes:
            - ${PWD}:/usr/src/app
        links:
            - db
    db:
        image: postgres
        env_file:
            - .env
        ports:
            - "5432:5432"
        restart: always