version: "3.5"
services:
    bot:
        build: .
        volumes:
            - ${PWD}:/usr/src/app
        links:
            - db
    db:
        image: postgres
        env_file:
            - .env
        ports:
            - "192.168.0.25:5432:5432"
        volumes:
            - ./postgres/data:/var/lib/postgresql/data
        restart: always